#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PandC_Mobile.Resource", IsApplication=true)]

namespace PandC_Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon1 = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002e
			public const int actionMenuView1 = 2131099694;
			
			// aapt resource value: 0x7f060001
			public const int btndetails = 2131099649;
			
			// aapt resource value: 0x7f06002a
			public const int button1 = 2131099690;
			
			// aapt resource value: 0x7f06002f
			public const int button2 = 2131099695;
			
			// aapt resource value: 0x7f060033
			public const int button3 = 2131099699;
			
			// aapt resource value: 0x7f060032
			public const int button4 = 2131099698;
			
			// aapt resource value: 0x7f060031
			public const int button5 = 2131099697;
			
			// aapt resource value: 0x7f060030
			public const int button6 = 2131099696;
			
			// aapt resource value: 0x7f060034
			public const int button7 = 2131099700;
			
			// aapt resource value: 0x7f060038
			public const int checkBox1 = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int checkBox2 = 2131099705;
			
			// aapt resource value: 0x7f06003d
			public const int checkBox3 = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int checkBox4 = 2131099710;
			
			// aapt resource value: 0x7f060005
			public const int editText1 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int editText2 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int editText3 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int editText4 = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int editText5 = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int editText6 = 2131099668;
			
			// aapt resource value: 0x7f06001e
			public const int get_address_button = 2131099678;
			
			// aapt resource value: 0x7f060000
			public const int gridLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06002b
			public const int imageView1 = 2131099691;
			
			// aapt resource value: 0x7f06003f
			public const int menuItem1 = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int menuItem2 = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int menuItem3 = 2131099713;
			
			// aapt resource value: 0x7f06002d
			public const int progressBar1 = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int relativeLayout1 = 2131099692;
			
			// aapt resource value: 0x7f060036
			public const int spCustomer = 2131099702;
			
			// aapt resource value: 0x7f060029
			public const int spinner1 = 2131099689;
			
			// aapt resource value: 0x7f060027
			public const int spinner2 = 2131099687;
			
			// aapt resource value: 0x7f060002
			public const int tableLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int tableRow1 = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int tableRow2 = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int tableRow3 = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow4 = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int tableRow5 = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int tableRow6 = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int tableRow7 = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int tableRow8 = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int tableRow9 = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int textView1 = 2131099677;
			
			// aapt resource value: 0x7f060035
			public const int textView10 = 2131099701;
			
			// aapt resource value: 0x7f060037
			public const int textView11 = 2131099703;
			
			// aapt resource value: 0x7f06003a
			public const int textView12 = 2131099706;
			
			// aapt resource value: 0x7f06001a
			public const int textView14 = 2131099674;
			
			// aapt resource value: 0x7f06001f
			public const int textView15 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int textView16 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int textView17 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int textView18 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int textView19 = 2131099683;
			
			// aapt resource value: 0x7f06001b
			public const int textView2 = 2131099675;
			
			// aapt resource value: 0x7f060024
			public const int textView20 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int textView21 = 2131099685;
			
			// aapt resource value: 0x7f06003c
			public const int textView27 = 2131099708;
			
			// aapt resource value: 0x7f060013
			public const int textView3 = 2131099667;
			
			// aapt resource value: 0x7f060028
			public const int textView4 = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int textView5 = 2131099686;
			
			// aapt resource value: 0x7f060016
			public const int textView8 = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int textView9 = 2131099672;
			
			// aapt resource value: 0x7f06003b
			public const int textViewtime = 2131099707;
			
			// aapt resource value: 0x7f06000d
			public const int tvCell = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int tvEmail = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int tvName = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int tvSurName = 2131099655;
			
			// aapt resource value: 0x7f06001c
			public const int tvTips = 2131099676;
			
			// aapt resource value: 0x7f06000a
			public const int tvtel = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClientCapture = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Lostool = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int scann = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int sla_offsite = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int sla_onsite = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int mainMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int menuItem1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int menuItem2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int menuItem3 = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
